#!/usr/bin/env php
<?php
namespace Transvision;

use VCS\Git;
use VCS\Mercurial;


if (php_sapi_name() != 'cli') {
    die('This command can only be used in CLI mode.');
}

include __DIR__ . '/../inc/init.php';

$target_repo = GIT . 'en-US';
$git = new DataMan($target_repo);

$moz_central  = new Mercurial(HG . 'TRUNK_EN-US/mozilla-central');
$comm_central = new Mercurial(HG . 'TRUNK_EN-US/comm-central');


//$data['mc'] = $moz_central->getCommits();
$data['cc'] = $comm_central->getCommits();

$sorted_timestamps = [];
$dirs_reference = [
    'browser', 'calendar', 'chat', 'devtools', 'dom', 'editor',
    'extensions', 'mail', 'mobile', 'netwerk', 'other-licenses',
    'security', 'services', 'suite', 'toolkit', 'webapprt'
];

$ext_reference = [
    'dtd', 'properties', 'ini', 'inc'
];

function sortByTimestamp($target, $commits, $name) {
    foreach ($commits as $commit) {
        $timestamp = $commit['date']->getTimestamp();

        // Handle edge case where two pushes occured at very same timestamp
        while(isset($target[$timestamp])) {
            $timestamp++;
        }
        $commit['repo'] = $name;
        $target[$timestamp] = $commit;
    }
    return $target;
}

$sorted_timestamps = sortByTimestamp($sorted_timestamps, $data['cc'], 'cc');
unset($data['cc']);
//$sorted_timestamps = sortByTimestamp($sorted_timestamps, $data['mc'], 'mc');
unset($data['mc']);

ksort($sorted_timestamps);

foreach ($sorted_timestamps as $commit) {
    $l10n_has_changed = false;
    $rev = explode(':', $commit['commit'])[1];

    switch($commit['repo']) {
        case 'cc':
            $vcs = $comm_central;
            $web_link = 'comm-central';
            break;
        case 'mc':
            $vcs = $moz_central;
            $web_link = 'mozilla-central';
            break;
    }
    $changes = $vcs->getChangedFiles($rev);

    foreach ($changes as $change) {
        if (! Strings::startsWith($change['path'], $dirs_reference)
         || ! Strings::endsWith($change['path'], $ext_reference)) {
            continue;
        }

        $vcs->revertFile($rev, $change['path']);
        $l10n_has_changed = true;

        $target_path = $target_repo . '/' . $change['path'];

        switch($change['type']) {
            case 'A':
            case 'M':
                Files::fileForceContents(
                    $target_path,
                    file_get_contents($vcs->repository_path . '/' . $change['path'])
                );
                break;
            case 'R':
                unlink($target_path);
                break;
        }
    }

    // If this commit has l10n changes, record it
    if ($l10n_has_changed) {
        $message = $commit['summary'] . "\nhttps://hg.mozilla.org/{$web_link}/rev/{$rev}";
        $author = $commit['author'] . ' <' . $commit['email'] . '>';
        $date = $commit['date']->format('D M j H:i:s Y O');
        $git->commit($message, $author, $date);
    }
}
