#!/usr/bin/env php
<?php
namespace Transvision;

use VCS\Git;
use VCS\Mercurial;


if (php_sapi_name() != 'cli') {
    die('This command can only be used in CLI mode.');
}

include __DIR__ . '/../inc/init.php';

function sortByTimestamp($target, $commits, $name) {
    foreach ($commits as $commit) {
        $timestamp = $commit['date']->getTimestamp();

        // Handle edge case where two pushes occured at very same timestamp
        while(isset($target[$timestamp])) {
            $timestamp++;
        }
        $commit['repo'] = $name;
        $target[$timestamp] = $commit;
    }
    return $target;
}

function linkBugstoBugzilla($string) {
    $bugs = [];
    preg_match_all("/Bug ?([0-9]+)\b/i", $string, $bugs);

    $n = 0;
    foreach ($bugs[0] as $bug_as_string) {
        $bz_link = 'https://bugzil.la/' . $bugs[1][$n];
        $string = str_replace($bug_as_string, $bz_link, $string);
        $n++;
    }

    return $string;
}

$moz_central_dirs = [
    'browser/branding/official/locales/en-US' => 'browser/branding/official',
    'browser/locales/en-US'                   => 'browser',
    'browser/extensions/pocket/locales/en-US' => 'browser/extensions/pocket',
    'devtools/client/locales/en-US'           => 'devtools/client',
    'devtools/shared/locales/en-US'           => 'devtools/shared',
    'dom/locales/en-US'                       => 'dom',
    'embedding/android/locales/en-US'         => 'embedding/android',
    'mobile/android/base/locales/en-US'       => 'mobile/android/base',
    'mobile/android/locales/en-US/chrome'     => 'mobile/android/chrome',
    'mobile/locales/en-US'                    => 'mobile',
    'netwerk/locales/en-US'                   => 'netwerk',
    'security/manager/locales/en-US/chrome'   => 'security/manager/chrome',
    'services/sync/locales/en-US'             => 'services/sync',
    'toolkit/locales/en-US'                   => 'toolkit',
    'webapprt/locales/en-US'                  => 'webapprt'
];
// If we want to include en-US dic history: extensions/spellcheck/locales/en-US
// Not sure we want to handle that… (from CVS, removed in sept 2008) http://hg.mozilla.org/mozilla-central/file/9b2a99adc05e/embedding/browser/chrome/locale/en-US

$comm_central_dirs = [
    'calendar/locales/en-US'                            => 'calendar',
    'chat/locales/en-US'                                => 'chat',
    'editor/ui/locales/en-US/chrome'                    => 'editor/ui/chrome',
    'mail/locales/en-US'                                => 'mail',
    'other-licenses/branding/thunderbird/locales/en-US' => 'other-licenses/branding/thunderbird',
    'other-licenses/branding/sunbird/locales/en-US'     => 'other-licenses/branding/sunbird',
    'suite/locales/en-US'                               => 'suite'
];


$target_repo = GIT . 'en-US';
$git = new DataManager($target_repo);

$moz_central = new HgRepo(HG . 'TRUNK_EN-US/mozilla-central');
$moz_central->short_name  = 'mozilla-central';
$moz_central->web_link    = 'mozilla-central';
$moz_central->origin      = 'Mozilla Central';
$moz_central->repo_dirs   = $moz_central_dirs;
$moz_central->save_latest = CACHE_PATH . 'latest_' . $moz_central->short_name . '.txt';

$comm_central = new HgRepo(HG . 'TRUNK_EN-US/comm-central');
$comm_central->short_name  = 'comm-central';
$comm_central->web_link    = 'comm-central';
$comm_central->origin      = 'Comm Central';
$comm_central->repo_dirs   = $comm_central_dirs;
$comm_central->save_latest = CACHE_PATH . 'latest_' . $comm_central->short_name . '.txt';


$moz_central->getHistory();
$comm_central->getHistory();

print ('##### Got history');

$sorted_timestamps = [];

if (! empty($comm_central->data)) {
    $sorted_timestamps = sortByTimestamp($sorted_timestamps, $comm_central->data, $comm_central->short_name);
    $comm_central->data = [];
}
if (! empty($moz_central->data)) {
    $sorted_timestamps = sortByTimestamp($sorted_timestamps, $moz_central->data, $moz_central->short_name);
    $moz_central->data = [];
}

ksort($sorted_timestamps);
print ('##### History sorted!');
foreach ($sorted_timestamps as $commit) {
    $l10n_has_changed = false;
    $rev = explode(':', $commit['commit'])[1];

    $vcs = $moz_central;
    if ($commit['repo'] == $comm_central->short_name) {
        $vcs = $comm_central;
    }

    $vcs->rev = $rev;
    $changes = $vcs->getChangedFiles($rev);
    $first_change = true;
    foreach ($changes as $change) {
        // Quick check to eliminate files outside l10n directories
        if (! Strings::startsWith($change['path'], array_keys($vcs->repo_dirs))) {
            continue;
        }

        if ($first_change) {
            // Checkout the repo to the current revision
            $first_change = false;
            $vcs->revertRepo($rev);
        }
        $l10n_has_changed = true;

        // Get from which source directory the file is coming
        foreach ($vcs->repo_dirs as $source => $target) {
            if (Strings::startsWith($change['path'], $source)) {
                $source_dir = $source;
                $target_dir = $target;
            }
        }

        // Build target path by switching dirs and adding target repo
        $target_path = str_replace($source_dir, $target_dir, $change['path']);
        $target_path = $target_repo . '/' . $target_path;

        // Check the type of change and copy / delete the file to/from target repo
        switch($change['type']) {
            case 'A':
            case 'M':
                Files::fileForceContents(
                    $target_path,
                    file_get_contents($vcs->repository_path . '/' . $change['path'])
                );
                break;
            case 'R':
                /*
                    Remove the file only if it exists (merges are listing
                    already deleted files)
                */
                if (is_file($target_path)) {
                    unlink($target_path);
                }
                break;
        }
    }

    /*
        If this commit has l10n files listed in its changed files and actually
        changed those files, record it
    */
    if ($l10n_has_changed && ! empty($git->status())) {
        $commit['summary'] = linkBugstoBugzilla($commit['summary']);
        $message = $commit['summary'] . "\n\nDiff on {$vcs->origin}: https://hg.mozilla.org/{$vcs->web_link}/rev/{$rev}";
        $author  = $commit['author'] . ' <' . $commit['email'] . '>';
        $date    = $commit['date']->format('D M j H:i:s Y O');
        $git->commit($message, $author, $date);
    }
}

if (isset($moz_central->rev)) {
    file_put_contents($moz_central->save_latest, $moz_central->rev);
}
if (isset($comm_central->rev)) {
    file_put_contents($comm_central->save_latest, $comm_central->rev);
}